language: r
r:
  - release
  - devel
cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov(function_exclusions = c("rstan_package_skeleton", "init_cpp"))'
